/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "2.0.1-401-g98729aa794"
#endif /* AVUTIL_FFVERSION_H */
